# Generated by Django 5.1.7 on 2025-05-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='isRead',
            field=models.BooleanField(default=False),
        ),
    ]
