# Generated by Django 5.1.7 on 2025-05-13 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
    ]
