# Generated by Django 5.1.7 on 2025-05-14 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_commentcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('student', 'Student'), ('teacher', 'Teacher')], default='student', max_length=10),
        ),
    ]
